-- MySQL Script generated by MySQL Workbench
-- Sat Oct  8 21:28:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EPS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EPS` (
  `idEPS` INT NOT NULL,
  `Nombre_EPS` VARCHAR(45) NULL,
  `Nombre_IPS` VARCHAR(45) NULL,
  `IdEmpleadoEPS` VARCHAR(45) NULL,
  `Nombre_Empleado_EPS` VARCHAR(45) NULL,
  PRIMARY KEY (`idEPS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `Documento` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Tipo_documento` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `Nacionalidad` VARCHAR(45) NULL,
  `EPS` VARCHAR(45) NULL,
  `IPS` VARCHAR(45) NULL,
  `Numero_Solicitud` VARCHAR(45) NULL,
  `Tipo_Solicitud` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Tipo_Plan` VARCHAR(45) NULL,
  `EPS_idEPS` INT NOT NULL,
  PRIMARY KEY (`Documento`),
  INDEX `fk_Usuario_EPS_idx` (`EPS_idEPS` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_EPS`
    FOREIGN KEY (`EPS_idEPS`)
    REFERENCES `mydb`.`EPS` (`idEPS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `mydb`.`Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personal` (
  `id_Empleado` INT NOT NULL,
  `Nombre_Empleado` VARCHAR(45) NULL,
  `Documento_Empleado` VARCHAR(45) NULL,
  `Telefono_Empleado` VARCHAR(45) NULL,
  `IDZona` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`id_Empleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `mydb`.`Zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zonas` (
  `IDZona` INT NOT NULL,
  `Nombre_Zona` VARCHAR(45) NULL,
  `Localidad` VARCHAR(45) NULL,
  `Barrio` VARCHAR(45) NULL,
  `Personal_id_Empleado` INT NOT NULL,
  PRIMARY KEY (`IDZona`),
  INDEX `fk_Zonas_Personal1_idx` (`Personal_id_Empleado` ASC) VISIBLE,
  CONSTRAINT `fk_Zonas_Personal1`
    FOREIGN KEY (`Personal_id_Empleado`)
    REFERENCES `mydb`.`Personal` (`id_Empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Solicitudes` (
  `idSolicitud` INT NOT NULL,
  `TipoSolicitud` VARCHAR(45) NULL,
  `Fecha_Solicitud` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Personal_id_Empleado` INT NOT NULL,
  `IDZona` INT ZEROFILL NOT NULL,
  `Zonas_IDZona` INT NOT NULL,
  PRIMARY KEY (`idSolicitud`),
  INDEX `fk_Solicitudes_Personal1_idx` (`Personal_id_Empleado` ASC) VISIBLE,
  INDEX `fk_Solicitudes_Zonas1_idx` (`Zonas_IDZona` ASC) VISIBLE,
  CONSTRAINT `fk_Solicitudes_Personal1`
    FOREIGN KEY (`Personal_id_Empleado`)
    REFERENCES `mydb`.`Personal` (`id_Empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitudes_Zonas1`
    FOREIGN KEY (`Zonas_IDZona`)
    REFERENCES `mydb`.`Zonas` (`IDZona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `mydb`.`Medicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medicamentos` (
  `idMedicamentos` INT NOT NULL,
  `Nombre_medicamento` VARCHAR(45) NULL,
  `Cantidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idMedicamentos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `mydb`.`EPS_has_Solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EPS_has_Solicitudes` (
  `EPS_idEPS` INT NOT NULL,
  `Solicitudes_idSolicitud` INT NOT NULL,
  PRIMARY KEY (`EPS_idEPS`, `Solicitudes_idSolicitud`),
  INDEX `fk_EPS_has_Solicitudes_Solicitudes1_idx` (`Solicitudes_idSolicitud` ASC) VISIBLE,
  INDEX `fk_EPS_has_Solicitudes_EPS1_idx` (`EPS_idEPS` ASC) VISIBLE,
  CONSTRAINT `fk_EPS_has_Solicitudes_EPS1`
    FOREIGN KEY (`EPS_idEPS`)
    REFERENCES `mydb`.`EPS` (`idEPS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EPS_has_Solicitudes_Solicitudes1`
    FOREIGN KEY (`Solicitudes_idSolicitud`)
    REFERENCES `mydb`.`Solicitudes` (`idSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `mydb`.`Solicitudes_has_Medicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Solicitudes_has_Medicamentos` (
  `Solicitudes_idSolicitud` INT NOT NULL,
  `Medicamentos_idMedicamentos` INT NOT NULL,
  PRIMARY KEY (`Solicitudes_idSolicitud`, `Medicamentos_idMedicamentos`),
  INDEX `fk_Solicitudes_has_Medicamentos_Medicamentos1_idx` (`Medicamentos_idMedicamentos` ASC) VISIBLE,
  INDEX `fk_Solicitudes_has_Medicamentos_Solicitudes1_idx` (`Solicitudes_idSolicitud` ASC) VISIBLE,
  CONSTRAINT `fk_Solicitudes_has_Medicamentos_Solicitudes1`
    FOREIGN KEY (`Solicitudes_idSolicitud`)
    REFERENCES `mydb`.`Solicitudes` (`idSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitudes_has_Medicamentos_Medicamentos1`
    FOREIGN KEY (`Medicamentos_idMedicamentos`)
    REFERENCES `mydb`.`Medicamentos` (`idMedicamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
